// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG8YwzzXAliSeJKBKzWz6iMYJrl2hqK5k',
    appId: '1:858735033983:web:dc53c7783a93136b28494a',
    messagingSenderId: '858735033983',
    projectId: 'flash-chat-51867',
    authDomain: 'flash-chat-51867.firebaseapp.com',
    storageBucket: 'flash-chat-51867.appspot.com',
    measurementId: 'G-8JXS1LM5F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY1X3Z97JL5SsbMZ_Say3g4npkY2ptBVk',
    appId: '1:858735033983:android:cb24d8c182f4a5b728494a',
    messagingSenderId: '858735033983',
    projectId: 'flash-chat-51867',
    storageBucket: 'flash-chat-51867.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXC2APSVcdc2BrOOL7176S-Lk33S8LU3Y',
    appId: '1:858735033983:ios:1eb23f21dc77352528494a',
    messagingSenderId: '858735033983',
    projectId: 'flash-chat-51867',
    storageBucket: 'flash-chat-51867.appspot.com',
    iosBundleId: 'com.example.flashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXC2APSVcdc2BrOOL7176S-Lk33S8LU3Y',
    appId: '1:858735033983:ios:b3fea7662941c31328494a',
    messagingSenderId: '858735033983',
    projectId: 'flash-chat-51867',
    storageBucket: 'flash-chat-51867.appspot.com',
    iosBundleId: 'com.example.flashchat.RunnerTests',
  );
}
