// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYSedr8Amm4uIFWmS7PYzAvjm9SKLGVKU',
    appId: '1:377812473523:web:6505d058e908fe413cc2c6',
    messagingSenderId: '377812473523',
    projectId: 'safesphere-99830',
    authDomain: 'safesphere-99830.firebaseapp.com',
    storageBucket: 'safesphere-99830.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXnYlvBsBw52l_ZULZrZYQGx23w5gNBAI',
    appId: '1:377812473523:android:c4e61ffcb85a86053cc2c6',
    messagingSenderId: '377812473523',
    projectId: 'safesphere-99830',
    storageBucket: 'safesphere-99830.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd3vZZv09qgkyuRFB7D_NIVfofAoid4O0',
    appId: '1:377812473523:ios:de5c6162c391ca983cc2c6',
    messagingSenderId: '377812473523',
    projectId: 'safesphere-99830',
    storageBucket: 'safesphere-99830.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd3vZZv09qgkyuRFB7D_NIVfofAoid4O0',
    appId: '1:377812473523:ios:e6131c43a100ed373cc2c6',
    messagingSenderId: '377812473523',
    projectId: 'safesphere-99830',
    storageBucket: 'safesphere-99830.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
